Cache charmcraft pack container, skip unstable tests except on schedule
canonical/mongodb-k8s-operator pull request #109
Opened 2023-02-17 18:29 UTC by carlcsaposs-canonical

Ported from https://github.com/canonical/mysql-k8s-operator/pull/146

2023-02-21 14:48 UTC, delgod requested changes

2023-02-21 14:48 UTC, delgod commented on .github/workflows/ci.yaml
> +          - integration-tls
I think we need rename tests names in tox. currently we test nothing

2023-02-23 13:51 UTC, MiaAltieri approved these changes
looks good to me, curious why that TLS test is failing, I think its related to the issue paolo mentioned last week

2023-02-24 14:57 UTC, delgod approved these changes

2023-02-24 16:08 UTC, merged