Update link to documentation for MongoDB 6 charm
canonical/mongodb-k8s-operator pull request #215
Opened 2023-11-08 13:08 UTC by dmitry-ratushnyy

# Issue

After publishing a new charm with MongoDB 6 we need to support different docs sets for different version of charms.

# Solution

Update link to documentation set in metadata.yaml

2023-11-08 13:16 UTC, MiaAltieri approved these changes

2023-11-08 13:17 UTC, delgod requested changes

2023-11-08 13:17 UTC, delgod commented on pyproject.toml
> +repository = "https://github.com/python-poetry/poetry"
```suggestion
homepage = "https://charmhub.io/mongodb-k8s?channel=6/edge"
repository = "https://github.com/canonical/mongodb-k8s-operator"
```

2023-11-08 13:32 UTC, delgod approved these changes

2023-11-10 06:37 UTC, MiaAltieri approved these changes

2023-11-10 06:42 UTC, merged