Support backups sc
canonical/mongodb-k8s-operator pull request #289
Opened 2024-08-01 06:02 UTC by MiaAltieri

2024-08-02 12:46 UTC, MiaAltieri commented on tests/integration/backup_tests/helpers.py
> -async def destroy_cluster(ops_test: OpsTest, cluster_name: str) -> None:
moved this to reflect @Gu1nness change

2024-08-02 12:46 UTC, MiaAltieri commented on tests/integration/backup_tests/helpers.py
> -    access_key = os.environ.get(f"{cloud}_ACCESS_KEY", False)
updating to new use of secrets

2024-08-02 12:46 UTC, MiaAltieri commented on tests/integration/backup_tests/helpers.py
> +async def get_backup_list(ops_test: OpsTest, db_app_name=None) -> str:
copied from VM

2024-08-02 12:46 UTC, MiaAltieri commented on tests/integration/backup_tests/test_sharding_backups.py
> +# See LICENSE file for licensing details.
copied with minor modifications from VM charm (with @Gu1nness recent improvements to tests)

2024-08-02 12:46 UTC, MiaAltieri commented on tests/integration/helpers.py
> +async def destroy_cluster(ops_test: OpsTest, applications: list[str]) -> None:
copied from VM charm

2024-08-02 12:46 UTC, MiaAltieri commented on tests/integration/sharding_tests/writes_helpers.py
> +# See LICENSE file for licensing details.
copied from VM charm with slight mods

2024-08-02 13:54 UTC, Gu1nness approved these changes, later dismissed
One very minor suggestion here (not important, just nitpicking)

2024-08-02 13:54 UTC, Gu1nness commented on tests/integration/helpers.py
> +    ops_test: OpsTest, unit_id: int = 0, username="operator", app_name: str = APP_NAME
```suggestion
    ops_test: OpsTest, unit_id: int = 0, username : str = "operator", app_name: str = APP_NAME
```

2024-08-05 07:29 UTC, Gu1nness approved these changes, later dismissed

2024-08-05 08:19 UTC, Gu1nness commented
@MiaAltieri Just saw that:
```
  /home/runner/work/mongodb-k8s-operator/mongodb-k8s-operator/tests/integration/backup_tests/test_backups.py:155: RuntimeWarning: coroutine 'Model.wait_for_idle' was never awaited
```
in the test failing

2024-08-05 08:47 UTC, Mehdi-Bendriss requested changes
Thanks Mia - I have a few comments

2024-08-05 08:47 UTC, Mehdi-Bendriss commented on tests/integration/backup_tests/test_backups.py
> +    ops_test.model.wait_for_idle(apps=[S3_APP_NAME], status="active")
```suggestion
    await ops_test.model.wait_for_idle(apps=[S3_APP_NAME], status="active")
```

2024-08-05 08:47 UTC, Mehdi-Bendriss commented on tests/integration/backup_tests/test_backups.py
A few lines above (line 352) - There is a reference to a non-existing function: `ha_helpers.count_writes(ops_test)`

2024-08-05 08:47 UTC, Mehdi-Bendriss commented on tests/integration/backup_tests/test_backups.py
>              writes_in_new_cluster == writes_in_old_cluster
A few lines above (line 458) - There is a reference to a non-existing function: `ha_helpers.count_writes(ops_test)`

2024-08-05 08:47 UTC, Mehdi-Bendriss commented on tests/integration/backup_tests/test_backups.py
> +    await destroy_cluster(ops_test, cluster_name=NEW_CLUSTER)
```suggestion
    await destroy_cluster(ops_test, applications=[NEW_CLUSTER])
```

2024-08-05 08:47 UTC, Mehdi-Bendriss commented on tests/integration/backup_tests/helpers.py
>      test_collection.insert_one({"unwanted_data": "bad data 2"})
We should delete this helper. It seems to be a broken precursor (reference to missing functions etc..) of the one you added below

2024-08-05 08:47 UTC, Mehdi-Bendriss commented on tests/integration/ha_tests/application_charm/src/charm.py
> +        if len(data) == 0:
nit - good candidate for the walrus operator:
```suggestion
        if not (data := list(self.database.fetch_relation_data().values())):
```

2024-08-05 08:47 UTC, Mehdi-Bendriss commented on tests/integration/sharding_tests/writes_helpers.py
> +) -> bool:
```suggestion
) -> None:
```

2024-08-05 12:18 UTC, Mehdi-Bendriss approved these changes

2024-08-05 12:22 UTC, Gu1nness approved these changes

2024-08-05 12:22 UTC, merged