Dpe 5237 revision check
canonical/mongodb-k8s-operator pull request #331
Opened 2024-09-12 07:49 UTC by MiaAltieri

2024-09-12 12:31 UTC, Gu1nness approved these changes, later dismissed

2024-09-12 16:42 UTC, Mehdi-Bendriss approved these changes

2024-09-12 16:44 UTC, Mehdi-Bendriss requested changes

2024-09-12 16:44 UTC, Mehdi-Bendriss commented on tests/integration/upgrades/test_revision_check.py
> +async def test_local_config_server_reports_remote_shard(ops_test: OpsTest) -> None:
```suggestion
@pytest.mark.group(1)
@pytest.mark.abort_on_fail
async def test_local_config_server_reports_remote_shard(ops_test: OpsTest) -> None:
```

2024-09-12 16:44 UTC, Mehdi-Bendriss commented on tests/integration/upgrades/test_revision_check.py
> +async def test_local_shard_reports_remote_config_server(ops_test: OpsTest) -> None:
```suggestion
@pytest.mark.group(1)
@pytest.mark.abort_on_fail
async def test_local_shard_reports_remote_config_server(ops_test: OpsTest) -> None:
```

2024-09-13 07:20 UTC, Gu1nness approved these changes, later dismissed

2024-09-13 11:54 UTC, Mehdi-Bendriss approved these changes

2024-09-13 15:35 UTC, Gu1nness approved these changes

2024-09-13 15:35 UTC, merged