Dpe 5369 sc int tests for upgrades
canonical/mongodb-k8s-operator pull request #333
Opened 2024-09-16 15:03 UTC by MiaAltieri

2024-09-18 07:45 UTC, Gu1nness approved these changes

2024-09-18 07:46 UTC, Gu1nness requested changes

2024-09-18 07:46 UTC, Gu1nness commented on tests/integration/upgrades/test_upgrades.py
> +# @pytest.mark.skip("skip until upgrades work has been released to charmhub")
Needs to be skipped since the deploy is skipped as well

2024-09-18 07:55 UTC, Gu1nness approved these changes, later dismissed

2024-09-20 06:08 UTC, delgod commented on tests/integration/ha_tests/application_charm/actions.yaml
> +      description: continuous_writes_collection
maybe
```suggestion
      type: string
      description: name of the collection to write to
      default: continuous_writes_collection
```

2024-09-20 13:59 UTC, Gu1nness approved these changes, later dismissed

2024-09-22 20:30 UTC, Mehdi-Bendriss approved these changes, later dismissed

2024-09-23 08:26 UTC, Gu1nness submitted a review, later dismissed

2024-09-26 16:09 UTC, Gu1nness approved these changes

2024-10-02 11:17 UTC, Mehdi-Bendriss approved these changes

2024-10-02 15:09 UTC, merged