Adding full cluster crash/restart test
canonical/mongodb-k8s-operator pull request #80
Opened 2022-12-02 15:29 UTC by dragomirp

# Cluster crash test failures:
Cluster crash/restart currently fail the assertion for total writes, meaning that the DB didn't persist some of the writes `continuous_writes.py` thinks it should have.

The cause for the mismatch seems to be a PyMongo OperationError thrown while restarted nodes rejoin the cluster with the following message:
```
No keys found for HMAC that is valid for time: { ts: Timestamp(1669922958, 10) } with id: 7172123513443057669, full error: {'ok': 0.0, 'errmsg': 'No keys found for HMAC that is valid for time: { ts: Timestamp(1669922958, 10) } with id: 7172123513443057669', 'code': 211, 'codeName': 'KeyNotFound'}
```

## Steps to reproduce manually
* Deploy a cluster of three mongodb-k8s units
* Deploy the HA test charm from /tests/integration/ha_tests/application_charm
* Create a layer configuration to prevent pebble from restarting the service and upload it to the MongoDB units in the mongod container:
```
services:
  mongod:
    override: merge
    on-success: ignore
    on-failure: ignore
```
* Add the layer to pebble and replan:
```
/charm/bin/pebble add test2 <your_layer_config_location>
/charm/bin/pebble replan
```
* Kill all mongod processes in all the units
* Replan the services to restart them and check the output of `continuous_writes.py`. You should get errors about the time the second or third node rejoins.

## Potentially related log output from mongod logs:
```
2022-12-01T11:32:55.643Z [mongod] {"t":{"$date":"2022-12-01T11:32:55.643+00:00"},"s":"I",  "c":"-",
  "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"ReadConcernMajorityNotAvailableYet: Read concern majority reads are currently not possible.","nextWakeupMillis":600}}
```
```
2022-12-01T13:37:22.043Z [mongod] {"t":{"$date":"2022-12-01T13:37:22.042+00:00"},"s":"I",  "c":"CONTROL",  "id":20714,   "ctx":"LogicalSessionCacheRefresh","msg":"Failed to refresh session cache, will try again at the next refresh interval","attr":{"error":"NotYetInitialized: Replication has not yet been configured"}}
```

## Potentially related issues:
* [Same error, but seems to be for older MongoDB versions](https://jira.mongodb.org/browse/SERVER-47568)
* [Same error, more recent version](https://stackoverflow.com/questions/70518350/mongodb-replicaset-failed-to-refresh-key-cache)
* [Same error while changing storage engine](https://www.mongodb.com/community/forums/t/adding-wiredtiger-node-to-mmapv1-replica-set-leads-to-no-keys-found-for-hmac/5167)
* [Same error while trying to convert cluster to replicaset](https://stackoverflow.com/questions/60876115/error-while-converting-a-mongodb-cluster-into-a-replica-set/65909771#65909771)

2023-04-10 12:27 UTC, delgod requested changes

2023-04-10 12:27 UTC, delgod commented on tests/integration/ha_tests/helpers.py
> +                        f"run --unit {unit.name} ps aux | grep {MONGOD_PROCESS_NAME}"
```suggestion
                        f"run --unit {unit.name} pgrep -x {MONGOD_PROCESS_NAME}"
```

2023-04-14 11:07 UTC, delgod approved these changes

2023-08-24 09:08 UTC, dragomirp commented
Superseded by https://github.com/canonical/mongodb-k8s-operator/pull/190

2023-08-24 09:08 UTC, closed without merging